export const chocolates = [
  {
    id: 1,
    name: "Chocolate Bar",
    price: 2.99,
    description: "A delicious chocolate bar.",
    image: "/products/chocolates/chocolate-1.jpg",
    alt: "",
  },
  {
    id: 2,
    name: "Chocolate Cake",
    price: 5.99,
    description: "A moist and delicious chocolate cake.",
    image: "/products/chocolates/chocolate-2.jpg",
    alt: "",
  },
  {
    id: 3,
    name: "Chocolate Mousse",
    price: 7.99,
    description: "A light and airy chocolate mousse.",
    image: "/products/chocolates/chocolate-3.jpg",
    alt: "",
  },
  {
    id: 4,
    name: "Chocolate Mousse",
    price: 7.99,
    description: "A light and airy chocolate mousse.",
    image: "/products/chocolates/chocolate-4.jpg",
    alt: "",
  },
  {
    id: 5,
    name: "Chocolate Mousse",
    price: 7.99,
    description: "A light and airy chocolate mousse.",
    image: "/products/chocolates/chocolate-5.jpg",
    alt: "",
  },
  {
    id: 6,
    name: "Chocolate Mousse",
    price: 7.99,
    description: "A light and airy chocolate mousse.",
    image: "/products/chocolates/chocolate-6.jpg",
    alt: "",
  },
];

export const cupcakes = [
  {
    id: 1,
    name: "Vanilla Cupcake",
    price: 2.99,
    description: "A delicious vanilla cupcake.",
    image: "/products/cupcakes/cupcake-1.jpg",
    alt: "",
  },
  {
    id: 2,
    name: "Chocolate Cupcake",
    price: 2.99,
    description: "A delicious chocolate cupcake.",
    image: "/products/cupcakes/cupcake-2.jpg",
    alt: "",
  },
  {
    id: 3,
    name: "Red Velvet Cupcake",
    price: 3.99,
    description: "A delicious red velvet cupcake.",
    image: "/products/cupcakes/cupcake-3.jpg",
    alt: "",
  },
];

export const cookies = [
  {
    id: 1,
    name: "Chocolate Bar",
    price: 2.99,
    description: "A delicious chocolate bar.",
    image: "/products/cookies/cookie-1.jpg",
    alt: "",
  },
  {
    id: 2,
    name: "Chocolate Cake",
    price: 5.99,
    description: "A moist and delicious chocolate cake.",
    image: "/products/cookies/cookie-2.jpg",
    alt: "",
  },
  {
    id: 3,
    name: "Chocolate Mousse",
    price: 7.99,
    description: "A light and airy chocolate mousse.",
    image: "/products/cookies/cookie-3.jpg",
    alt: "",
  },
  {
    id: 4,
    name: "Chocolate Mousse",
    price: 7.99,
    description: "A light and airy chocolate mousse.",
    image: "/products/cookies/cookie-4.jpg",
    alt: "",
  },
  {
    id: 5,
    name: "Chocolate Mousse",
    price: 7.99,
    description: "A light and airy chocolate mousse.",
    image: "/products/cookies/cookie-5.jpg",
    alt: "",
  },
  {
    id: 6,
    name: "Chocolate Mousse",
    price: 7.99,
    description: "A light and airy chocolate mousse.",
    image: "/products/cookies/cookie-6.jpg",
    alt: "",
  },
];